// The other direction of the interop pin: envelopes this browser code produced,
// committed, and opened by Go.
//
// vectors.spec.ts proves the browser reproduces Go's bytes from Go's inputs.
// That is most of the story, but not the end of it: it exercises only the
// salts, nonces and entropy Go happened to choose. This file commits envelopes
// built here — with our own randomness, our own Recovery Key generator and our
// own encoder — and pkg/keys/browservectors_test.go opens every one of them.
// If the browser ever produces something Go cannot read, that test fails,
// rather than a user discovering it during a recovery.
//
// Regenerate with `pnpm vectors`. The output changes on every run by design
// (fresh salt, nonce and entropy), so regenerate only when adding a case —
// a diff full of new random bytes hides the one line that mattered.
import { readFileSync, writeFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { base64Decode, base64Encode, bytesToHex, equalBytes, hexToBytes, randomBytes } from './bytes'
import {
  checkRecoveryEnvelope,
  DEFAULT_ARGON_PARAMS,
  MIN_ARGON_PARAMS,
  open,
  seal,
  WrapKind,
  type ArgonParams
} from './envelope'
import { decodeRecoveryKey, generateRecoveryKey } from './recoverykey'
import { DK_SIZE, performSetupCeremony } from './ceremony'

const VECTORS_PATH = 'testdata/browser-vectors.json'

interface BrowserVector {
  name: string
  note: string
  /**
   * recovery_key is a throwaway key for a throwaway envelope. It is committed
   * on purpose: without it Go cannot open the blob, and there is nothing behind
   * it to protect.
   */
  recovery_key: string
  data_key_hex: string
  envelope_b64: string
  argon: { time: number; memory_kib: number; lanes: number; salt_len: number }
  accepted_by_setup: boolean
}

interface BrowserVectorFile {
  _comment: string
  generated_by: string
  vectors: BrowserVector[]
}

interface Case {
  name: string
  note: string
  params: ArgonParams
  /** viaCeremony builds the envelope through the real ceremony, self-verify and all. */
  viaCeremony?: boolean
}

const cases: Case[] = [
  {
    name: 'ceremony-default-params',
    note: 'What a browser actually sends: performSetupCeremony with DEFAULT_ARGON_PARAMS.',
    params: DEFAULT_ARGON_PARAMS,
    viaCeremony: true
  },
  {
    name: 'policy-floor',
    note: 'The weakest envelope the API accepts — what a slow device would produce.',
    params: MIN_ARGON_PARAMS
  },
  {
    name: 'raised-costs',
    note: 'Costs above the default, to prove Go reads the parameters from the header rather than assuming them.',
    params: { time: 4, memoryKiB: 32 * 1024, lanes: 2, saltLen: 24 }
  }
]

async function build(testCase: Case): Promise<BrowserVector> {
  let recoveryKey: string
  let dataKey: Uint8Array
  let envelope: Uint8Array

  if (testCase.viaCeremony) {
    const ceremony = await performSetupCeremony(testCase.params)
    recoveryKey = ceremony.recoveryKey
    dataKey = ceremony.dataKey
    envelope = base64Decode(ceremony.request.wrapped_dk_rk)
  } else {
    const generated = generateRecoveryKey()
    recoveryKey = generated.display
    dataKey = randomBytes(DK_SIZE)
    envelope = await seal({
      plaintext: dataKey,
      secret: generated.secret,
      kind: WrapKind.RK,
      params: testCase.params
    })
  }

  let accepted = true
  try {
    checkRecoveryEnvelope(envelope)
  } catch {
    accepted = false
  }

  return {
    name: testCase.name,
    note: testCase.note,
    recovery_key: recoveryKey,
    data_key_hex: bytesToHex(dataKey),
    envelope_b64: base64Encode(envelope),
    argon: {
      time: testCase.params.time,
      memory_kib: testCase.params.memoryKiB,
      lanes: testCase.params.lanes,
      salt_len: testCase.params.saltLen
    },
    accepted_by_setup: accepted
  }
}

describe('browser-produced vectors', () => {
  if (process.env.UPDATE_BROWSER_VECTORS) {
    it('regenerates the committed file', async () => {
      const file: BrowserVectorFile = {
        _comment:
          'Generated by `pnpm vectors` in web/. Envelopes produced by the browser crypto and ' +
          'opened by pkg/keys/browservectors_test.go. The recovery keys are throwaway test ' +
          'keys, committed because Go needs them to open the blobs. Do not edit by hand.',
        generated_by: 'web/src/crypto/browservectors.spec.ts',
        vectors: []
      }
      for (const testCase of cases) {
        file.vectors.push(await build(testCase))
      }
      writeFileSync(VECTORS_PATH, JSON.stringify(file, null, 2) + '\n')
    })
    return
  }

  const file = JSON.parse(readFileSync(VECTORS_PATH, 'utf8')) as BrowserVectorFile

  it('covers every case', () => {
    expect(file.vectors.map((vector) => vector.name)).toEqual(cases.map((testCase) => testCase.name))
  })

  for (const vector of file.vectors) {
    it(`still opens ${vector.name}`, async () => {
      const envelope = base64Decode(vector.envelope_b64)
      const secret = decodeRecoveryKey(vector.recovery_key)
      const dataKey = await open(envelope, secret)
      expect(equalBytes(dataKey, hexToBytes(vector.data_key_hex))).toBe(true)
    })

    it(`records the parameters it was sealed with for ${vector.name}`, () => {
      const envelope = base64Decode(vector.envelope_b64)
      let accepted = true
      try {
        checkRecoveryEnvelope(envelope)
      } catch {
        accepted = false
      }
      expect(accepted).toBe(vector.accepted_by_setup)
    })
  }
})
