package config

import (
	"bytes"
	"log/slog"
	"reflect"
	"strings"
	"testing"
)

func TestDescribe_DefaultsAreTheValuesHeld(t *testing.T) {
	s := newSample()
	s.Listener.Tags = []string{"a", "b"}
	got := map[string]Variable{}
	for _, v := range Describe(s) {
		got[v.Name] = v
	}
	for name, want := range map[string]Variable{
		"T_ADDR":    {Section: "Listener", Type: "string", Default: ":8080"},
		"T_PATH":    {Section: "Listener", Type: "string", Default: ""},
		"T_TAGS":    {Section: "Listener", Type: "comma-separated list", Default: "a,b"},
		"T_ENABLE":  {Section: "Tuning", Type: "boolean", Default: "false"},
		"T_WORKERS": {Section: "Tuning", Type: "integer", Default: "2"},
		"T_BACKEND": {Section: "Tuning", Type: "one of `memory`, `disk`", Default: ""},
		"T_TOKEN":   {Section: "Tuning", Type: "secret", Default: "", Secret: true},
	} {
		v := got[name]
		v.Name, v.Doc = "", ""
		if v != want {
			t.Errorf("%s = %+v, want %+v", name, v, want)
		}
	}
}

func TestNames_InDeclarationOrder(t *testing.T) {
	want := []string{"T_ADDR", "T_PATH", "T_TAGS", "T_ENABLE", "T_WORKERS", "T_BACKEND", "T_TOKEN"}
	if got := Names(newSample()); !reflect.DeepEqual(got, want) {
		t.Fatalf("Names = %v", got)
	}
}

// A section without a heading of its own belongs to the one around it, so a
// component can group its fields without changing the reference.
func TestDescribe_UntitledSectionsInherit(t *testing.T) {
	type inner struct {
		A string `env:"T_A" doc:"A."`
	}
	type root struct {
		Outer struct {
			Nested inner
		} `section:"Outer"`
	}
	if v := Describe(&root{}); v[0].Section != "Outer" {
		t.Fatalf("Section = %q", v[0].Section)
	}
}

// A secret's default would be a secret in the documentation.
func TestDescribe_RefusesASecretWithADefault(t *testing.T) {
	s := newSample()
	s.Tuning.Token = NewSecret("x")
	defer func() {
		if recover() == nil {
			t.Fatal("no panic")
		}
	}()
	Describe(s)
}

func TestEffective_EveryVariableOnceWithSecretsRedacted(t *testing.T) {
	value := randomValue(t)
	s := load(t, "T_TOKEN="+value, "T_ADDR=:9090")

	var buf bytes.Buffer
	slog.New(slog.NewJSONHandler(&buf, nil)).Info("configuration", "config", Effective(s))
	line := buf.String()
	if strings.Contains(line, value) {
		t.Fatalf("the line carries the secret: %s", line)
	}
	for _, want := range []string{`"t_addr":":9090"`, `"t_token":"` + redacted + `"`, `"t_path":""`, `"t_workers":2`} {
		if !strings.Contains(line, want) {
			t.Errorf("line lacks %s: %s", want, line)
		}
	}
}

func TestReference(t *testing.T) {
	ref := string(Reference(Program{
		Name:      "sample",
		Intro:     "A sample. Unrelated to T_PATH.",
		Config:    newSample(),
		Generator: "make generate",
	}))
	for _, want := range []string{
		`<!-- Generated by "make generate". Do not edit. -->`,
		"# Environment reference: sample",
		"## Listener",
		"## Tuning",
		"| `T_ADDR` | string | `:8080` | Address. |",
		"| `T_WORKERS` | integer | `2` | Workers. |",
		"| `T_TOKEN` | secret |  | Token. |",
	} {
		if !strings.Contains(ref, want) {
			t.Errorf("reference lacks %q:\n%s", want, ref)
		}
	}
}

func TestCodeNames(t *testing.T) {
	known := map[string]bool{"TLS_KEY_FILE": true}
	got := codeNames("Set with TLS_KEY_FILE, not TLS or TLS_KEY_FILES.", known)
	want := "Set with `TLS_KEY_FILE`, not TLS or TLS_KEY_FILES."
	if got != want {
		t.Fatalf("codeNames = %q, want %q", got, want)
	}
}
