package config

import (
	"bytes"
	"fmt"
	"regexp"
)

// Program is one binary's configuration, as its reference presents it.
type Program struct {
	// Name is the binary.
	Name string
	// Intro is a paragraph of Markdown introducing it.
	Intro string
	// Config is the binary's configuration root, a pointer to a struct
	// holding the defaults.
	Config any
	// Generator is the command that regenerates the page, named in its
	// header.
	Generator string
}

const referenceNotes = `
- **Booleans** are exactly ` + "`true`" + ` or ` + "`false`" + `. Anything else is refused at
  startup.
- **Integers** are non-negative.
- **Secrets** are never printed. A configuration line logged at startup shows
  ` + "`" + redacted + "`" + ` for a secret that is set, and nothing for one that is not. Take
  them from a Kubernetes Secret, not a ConfigMap.
- A value containing ` + "`" + PlaceholderMarker + "`" + ` (the shipped manifests' placeholder) is
  refused at startup.
- An empty value is the same as an unset one.
`

// Reference renders p's environment reference in Markdown.
func Reference(p Program) []byte {
	vars := Describe(p.Config)
	known := map[string]bool{"TZ": true}
	for _, v := range vars {
		known[v.Name] = true
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "<!-- Generated by %q. Do not edit. -->\n\n", p.Generator)
	fmt.Fprintf(&buf, "# Environment reference: %s\n\n%s\n%s", p.Name, p.Intro, referenceNotes)
	section := "\x00"
	for _, v := range vars {
		if v.Section != section {
			section = v.Section
			fmt.Fprintf(&buf, "\n## %s\n\n", section)
			buf.WriteString("| Variable | Type | Default | Description |\n|---|---|---|---|\n")
		}
		fmt.Fprintf(&buf, "| `%s` | %s | %s | %s |\n", v.Name, v.Type, defaultCell(v), codeNames(v.Doc, known))
	}
	return buf.Bytes()
}

func defaultCell(v Variable) string {
	if v.Default == "" {
		return ""
	}
	return "`" + v.Default + "`"
}

// envName matches what looks like an environment variable's name.
var envName = regexp.MustCompile(`\b[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*\b`)

// codeNames formats the names of known variables in a description as code.
func codeNames(doc string, known map[string]bool) string {
	return envName.ReplaceAllStringFunc(doc, func(word string) string {
		if known[word] {
			return "`" + word + "`"
		}
		return word
	})
}
