package config

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
)

// program is one binary's configuration, as the reference presents it.
type program struct {
	name  string
	intro string
	cfg   any
}

func programs() []program {
	return []program{
		{
			name: "backupd",
			intro: "The backup service, and its operator commands (`provision-state-space`, " +
				"`rotate-srw`, `rotate-tw`), which read the same configuration.",
			cfg: &Backupd{},
		},
		{
			name: "takeout",
			intro: "The admin's Take-Out extractor. Everything else it takes as flags; " +
				"no setting of it accepts key material.",
			cfg: &Takeout{},
		},
	}
}

// ReferencePath is where the generated reference lives, relative to the
// repository root.
const ReferencePath = "docs/reference/environment.md"

const referenceHeader = `<!-- Generated by "go generate ./internal/config" from internal/config. Do not edit. -->

# Environment reference

Every environment variable the binaries read. This page is generated from the
configuration structs, so it lists exactly what the code accepts.

- **Booleans** are exactly ` + "`true`" + ` or ` + "`false`" + `. Anything else is refused at
  startup.
- **Integers** are non-negative.
- **Secrets** are never printed. The configuration line the service logs at
  startup shows ` + "`" + redacted + "`" + ` for a secret that is set, and nothing for one that
  is not. Take them from a Kubernetes Secret, not a ConfigMap.
- A value containing ` + "`" + PlaceholderMarker + "`" + ` (the shipped manifests' placeholder) is
  refused at startup.
- An empty value is the same as an unset one.

The Go runtime also reads ` + "`TZ`" + ` (the zone schedules are read in, unless
` + "`SCHEDULE_TIMEZONE`" + ` says otherwise) and ` + "`SSL_CERT_DIR`" + ` / ` + "`SSL_CERT_FILE`" + ` (extra
CAs, for example for a backup target with a private certificate).
`

// Reference renders the environment reference in Markdown.
func Reference() []byte {
	var buf bytes.Buffer
	buf.WriteString(referenceHeader)
	for _, p := range programs() {
		vars := variables(reflect.ValueOf(p.cfg).Elem())
		known := map[string]bool{"TZ": true}
		for _, v := range vars {
			known[v.env] = true
		}

		fmt.Fprintf(&buf, "\n## %s\n\n%s\n", p.name, p.intro)
		section := "\x00"
		for _, v := range vars {
			if v.section != section {
				section = v.section
				fmt.Fprintf(&buf, "\n### %s\n\n", section)
				buf.WriteString("| Variable | Type | Default | Description |\n|---|---|---|---|\n")
			}
			fmt.Fprintf(&buf, "| `%s` | %s | %s | %s |\n",
				v.env, typeName(v), defaultCell(v), codeNames(v.doc, known))
		}
	}
	return buf.Bytes()
}

// typeName describes what a variable accepts.
func typeName(v variable) string {
	switch {
	case v.typ == secretType:
		return "secret"
	case v.typ == stringSliceType:
		return "comma-separated list"
	case len(v.values) > 0:
		return "one of `" + strings.Join(v.values, "`, `") + "`"
	case v.typ.Kind() == reflect.Bool:
		return "boolean"
	case v.typ.Kind() == reflect.Int:
		return "integer"
	default:
		return "string"
	}
}

func defaultCell(v variable) string {
	if v.def == "" {
		return ""
	}
	return "`" + v.def + "`"
}

// envName matches what looks like an environment variable's name.
var envName = regexp.MustCompile(`\b[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*\b`)

// codeNames formats the names of known variables in a description as code.
func codeNames(doc string, known map[string]bool) string {
	return envName.ReplaceAllStringFunc(doc, func(word string) string {
		if known[word] {
			return "`" + word + "`"
		}
		return word
	})
}
